### ISSUE TITLE
How to map 115,217 english categories into chinese categories?

### ISSUE THREAD

**Issue by saicoco** [ZhangYuanhan-AI/Bamboo#1]
I think the Bamboo is a great job. And I find the label system of Bamboo in README, also find the classification-demo on https://huggingface.co/spaces/CVPR/Bamboo_ViT-B16_demo, and I think it will be useful for me to build a subclass-chinese-classification system

I have a question, how to map the class-name of 115217-cls-model on huggingface into Bamboo-label-system:

for example,`bamboo['id2name_zh'][node_id]` can get the chinese-class-name, and I can get thee class-name of the classification by trainid2name.json. There is not a mapping between bamboo and trainid2name

Thanks!

**Comment by ZhangYuanhan-AI** [comment]
Very thanks for your interest!

Sorry, still confused. What do you mean by "There is not a mapping between bamboo and trainid2name". Can you give me a simple example?

**Comment by saicoco** [comment]
> Very thanks for your interest!
> 
> Sorry, still confused. What do you mean by "There is not a mapping between bamboo and trainid2name". Can you give me a simple example?

yes 😓

**Comment by ZhangYuanhan-AI** [comment]
I understand your question. Do you wanna ask about the mapping between train-id and node-id， say 1->nXXXX, 2->nXXX.

**Comment by ZhangYuanhan-AI** [comment]
> 

I think you can find what you want at :https://drive.google.com/drive/u/2/folders/19eL2NnPlKqANTFfH2tVJWYfYstywqzWZ

**Comment by saicoco** [comment]
Thanks!!!!!!,给你个大大的点赞
