### ISSUE TITLE
How to acquire Bamboo-DET

### ISSUE THREAD

**Issue by liliangqi** [ZhangYuanhan-AI/Bamboo#2]
Hi, I've read the paper about Bamboo. It is mentioned that Bamboo-CLS contains ~68M images and Bamboo-DET contains ~3M images. Is Bamboo-DET contained in Bamboo-CLS? I've downloaded all images of Bamboo-CLS, so what I need for Bamboo-DET is only the box-level annotation file?

**Comment by ZhangYuanhan-AI** [comment]
No. 

The images of Bamboo-DET and Bamboo-CLS are separated. We will open the Bamboo-DET very soon.

**Comment by liliangqi** [comment]
Thanks for response! There is another question. Categories in Bamboo are labeled with `visual` states in `id2state`, and the value could be 0, 1 or 2. I guess 1 and 2 represent visible and invisible objects, respectively. But how about 0?

**Comment by ZhangYuanhan-AI** [comment]
> 

0: non-visible
1: Visible
2: Unknown (some words are not ready for annotation)
