### ISSUE TITLE
Explore website link failed.

### ISSUE THREAD

**Issue by launchauto** [ZhangYuanhan-AI/Bamboo#4]
The explore website you posted in the project failed.
https://opengvlab.shlab.org.cn/bamboo/home
Would you update it later? I would like to get sample images of curtain categories in a convenient way.

**Comment by ZhangYuanhan-AI** [comment]
Now this website is reopen.

**Comment by twangnh** [comment]
seems invalid again

**Comment by ZhangYuanhan-AI** [comment]
> seems invalid again@ZhangYuanhan-AI

If you want to access to Bamboo. Please send your request to [yuanhan002@e.ntu.edu.sg](mailto:yuanhan002@e.ntu.edu.sg). The request should include your name and orgnization. We will notify you by email as soon as possible.

**Comment by twangnh** [comment]
noted and thanks for the reply!
